all:
  vars:
    install_avira: False
    avira_package_path: <local_absolute_path_to_the_NBAntiMalwareClient_x.y.zip>  # /home/avira/NBAntiMalwareClient_2.4.zip
    scan_user: scanuser
    scan_group: scangroup
    scan_user_password: "" # This password will be set/updated for the above scan_user

linuxScanHosts:
  vars:
    configure_nfs_client: True
    configure_smb_client: True
  hosts:
    <ip1/hostname1>:
      ansible_user: <username>
      ansible_ssh_pass: <password>

    <ip2/hostname2>:
      ansible_user: <username>
      ansible_ssh_pass: <password>

windowsScanHosts:
  vars:
    ansible_connection:  winrm
    ansible_winrm_port:  5985
    ansible_winrm_transport: ntlm
    ansible_winrm_server_cert_validation: validate

    configure_nfs: True
    install_vc_runtime: True
    override_openssh: False
    scan_vm_backup: False
    openssh_download_url: "https://github.com/PowerShell/Win32-OpenSSH/releases/download/v9.4.0.0p1-Beta/OpenSSH-Win64.zip"
  hosts:
    <ip1/hostname1>:
      ansible_user: <username>
      ansible_ssh_pass: <password>

    <ip2/hostname2>:
      ansible_user: <username>
      ansible_ssh_pass: <password>
